# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Dev/Madgwick_Quaternion_Filter_Unit/vip/axi4_lite_m_vip_0/axi4_lite_m_vip_0.xci
# IP: The module: 'axi4_lite_m_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/Madgwick_Quaternion_Filter_Unit/vip/axi4_lite_m_vip_0/axi4_lite_m_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_lite_m_vip_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Dev/Madgwick_Quaternion_Filter_Unit/vip/axi4_lite_m_vip_0/axi4_lite_m_vip_0.xci
# IP: The module: 'axi4_lite_m_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/Madgwick_Quaternion_Filter_Unit/vip/axi4_lite_m_vip_0/axi4_lite_m_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_lite_m_vip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
