# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MQFU_MicroBlaze/MQFU_MicroBlaze.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze || ORIG_REF_NAME==MQFU_MicroBlaze} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_microblaze_0_0/MQFU_MicroBlaze_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_microblaze_0_0 || ORIG_REF_NAME==MQFU_MicroBlaze_microblaze_0_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_dlmb_v10_0/MQFU_MicroBlaze_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_dlmb_v10_0 || ORIG_REF_NAME==MQFU_MicroBlaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_ilmb_v10_0/MQFU_MicroBlaze_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_ilmb_v10_0 || ORIG_REF_NAME==MQFU_MicroBlaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_dlmb_bram_if_cntlr_0/MQFU_MicroBlaze_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MQFU_MicroBlaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_ilmb_bram_if_cntlr_0/MQFU_MicroBlaze_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MQFU_MicroBlaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_lmb_bram_0/MQFU_MicroBlaze_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_lmb_bram_0 || ORIG_REF_NAME==MQFU_MicroBlaze_lmb_bram_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_xbar_0/MQFU_MicroBlaze_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_xbar_0 || ORIG_REF_NAME==MQFU_MicroBlaze_xbar_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_microblaze_0_axi_periph_0/MQFU_MicroBlaze_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MQFU_MicroBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_microblaze_0_axi_intc_0/MQFU_MicroBlaze_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MQFU_MicroBlaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_microblaze_0_xlconcat_0/MQFU_MicroBlaze_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MQFU_MicroBlaze_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_mdm_1_0/MQFU_MicroBlaze_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_mdm_1_0 || ORIG_REF_NAME==MQFU_MicroBlaze_mdm_1_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_clk_wiz_1_0/MQFU_MicroBlaze_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_clk_wiz_1_0 || ORIG_REF_NAME==MQFU_MicroBlaze_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_rst_clk_wiz_1_100M_0/MQFU_MicroBlaze_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MQFU_MicroBlaze_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_MQFU_AXI4_Lite_IP_0_0/MQFU_MicroBlaze_MQFU_AXI4_Lite_IP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_MQFU_AXI4_Lite_IP_0_0 || ORIG_REF_NAME==MQFU_MicroBlaze_MQFU_AXI4_Lite_IP_0_0} -quiet] -quiet

# IP: bd/MQFU_MicroBlaze/ip/MQFU_MicroBlaze_axi_uartlite_0_0/MQFU_MicroBlaze_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MQFU_MicroBlaze_axi_uartlite_0_0 || ORIG_REF_NAME==MQFU_MicroBlaze_axi_uartlite_0_0} -quiet] -quiet

# XDC: c:/Dev/Madgwick_Quaternion_Filter_Unit/MQFU_MicroBlaze_SoC/MQFU_MicroBlaze_SoC.gen/sources_1/bd/MQFU_MicroBlaze/MQFU_MicroBlaze_ooc.xdc
