# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.cache/wt [current_project]
set_property parent.project_path C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Dev/Madgwick_Quaternion_Filter_Unit/ip_repo/MQFU_AXI4_Lite_IP_1.0
  c:/Dev/Madgwick_Quaternion_Filter_Unit/ip_repo/MQFU_AXI_Lite_IP_1.0
  c:/Dev/Madgwick_Quaternion_Filter_Unit/ip_repo/MQFU_AXI4_Lite_IP_1.0
  c:/Dev/Madgwick_Quaternion_Filter_Unit/ip_repo/MQFU_AXI4_Lite_IP_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.runs/MQFU_AXI4_Lite_IP_synth_1 -new_name MQFU_AXI4_Lite_IP -ip [get_ips MQFU_AXI4_Lite_IP]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top MQFU_AXI4_Lite_IP -part xc7a100tcsg324-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix MQFU_AXI4_Lite_IP_ MQFU_AXI4_Lite_IP.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MQFU_AXI4_Lite_IP_stub.v
 lappend ipCachedFiles MQFU_AXI4_Lite_IP_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MQFU_AXI4_Lite_IP_stub.vhdl
 lappend ipCachedFiles MQFU_AXI4_Lite_IP_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MQFU_AXI4_Lite_IP_sim_netlist.v
 lappend ipCachedFiles MQFU_AXI4_Lite_IP_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MQFU_AXI4_Lite_IP_sim_netlist.vhdl
 lappend ipCachedFiles MQFU_AXI4_Lite_IP_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp MQFU_AXI4_Lite_IP.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips MQFU_AXI4_Lite_IP]
}

rename_ref -prefix_all MQFU_AXI4_Lite_IP_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MQFU_AXI4_Lite_IP.dcp
create_report "MQFU_AXI4_Lite_IP_synth_1_synth_report_utilization_0" "report_utilization -file MQFU_AXI4_Lite_IP_utilization_synth.rpt -pb MQFU_AXI4_Lite_IP_utilization_synth.pb"

if { [catch {
  file copy -force C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.runs/MQFU_AXI4_Lite_IP_synth_1/MQFU_AXI4_Lite_IP.dcp c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.runs/MQFU_AXI4_Lite_IP_synth_1/MQFU_AXI4_Lite_IP.dcp c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.runs/MQFU_AXI4_Lite_IP_synth_1/MQFU_AXI4_Lite_IP_stub.v c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.runs/MQFU_AXI4_Lite_IP_synth_1/MQFU_AXI4_Lite_IP_stub.vhdl c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.runs/MQFU_AXI4_Lite_IP_synth_1/MQFU_AXI4_Lite_IP_sim_netlist.v c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.runs/MQFU_AXI4_Lite_IP_synth_1/MQFU_AXI4_Lite_IP_sim_netlist.vhdl c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.ip_user_files/ip/MQFU_AXI4_Lite_IP]} {
  catch { 
    file copy -force c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_stub.v C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.ip_user_files/ip/MQFU_AXI4_Lite_IP
  }
}

if {[file isdir C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.ip_user_files/ip/MQFU_AXI4_Lite_IP]} {
  catch { 
    file copy -force c:/Dev/Madgwick_Quaternion_Filter_Unit/ip/MQFU_AXI4_Lite_IP/MQFU_AXI4_Lite_IP_stub.vhdl C:/Dev/Madgwick_Quaternion_Filter_Unit/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project/Madgwick_Quaternion_Filter_Unit_Vivado_2019_2_Project.ip_user_files/ip/MQFU_AXI4_Lite_IP
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
